version: "3.8"

services:
  api:
#    image: mjm/codica
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:pg_8008@postgres:5432/codica-tt
      NODE_ENV: developement
      PORT: 3000
    ports:
      - "8080:3000"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      DATABASE_NAME: "codica-tt"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "pg_8008"