version: "3.8"

services:
  api:
#    image: mjm/codica
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: developement
      PORT: 3000
    ports:
      - "8080:3000"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"